# Generated by Django 5.1.1 on 2024-10-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='completed',
            new_name='status',
        ),
    ]
