# Generated by Django 5.1.1 on 2024-10-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_completed_tasks_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
